apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- fluentbit-fluentbit-edge.yaml
- fluentbitconfig-fluentbitconfig-edge.yaml
- input-node-exporter-metrics.yaml
- input-prometheus-scrape.yaml
- output-stdout.yaml
- output-prometheus-remote-write.yaml

# Change to the namespace you want such as: 
# namespace: fluent
