apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- fluentbit-fluentBit.yaml
- fluentbitconfig-fluentBitConfig.yaml
- input-prometheusScrape.yaml
- output-stdout.yaml
- output-prometheusRemoteWrite.yaml

# Change to the namespace you want such as: 
# namespace: fluent
