// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"kubesphere.io/fluentbit-operator/apis/plugins/filter"
	"kubesphere.io/fluentbit-operator/apis/plugins/input"
	"kubesphere.io/fluentbit-operator/apis/plugins/output"
	"kubesphere.io/fluentbit-operator/apis/plugins/parser"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFilter) DeepCopyInto(out *ClusterFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFilter.
func (in *ClusterFilter) DeepCopy() *ClusterFilter {
	if in == nil {
		return nil
	}
	out := new(ClusterFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFilterList) DeepCopyInto(out *ClusterFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFilterList.
func (in *ClusterFilterList) DeepCopy() *ClusterFilterList {
	if in == nil {
		return nil
	}
	out := new(ClusterFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFilterSpec) DeepCopyInto(out *ClusterFilterSpec) {
	*out = *in
	if in.FilterItems != nil {
		in, out := &in.FilterItems, &out.FilterItems
		*out = make([]FilterItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFilterSpec.
func (in *ClusterFilterSpec) DeepCopy() *ClusterFilterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFluentBitConfig) DeepCopyInto(out *ClusterFluentBitConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFluentBitConfig.
func (in *ClusterFluentBitConfig) DeepCopy() *ClusterFluentBitConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterFluentBitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterFluentBitConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFluentBitConfigList) DeepCopyInto(out *ClusterFluentBitConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterFluentBitConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFluentBitConfigList.
func (in *ClusterFluentBitConfigList) DeepCopy() *ClusterFluentBitConfigList {
	if in == nil {
		return nil
	}
	out := new(ClusterFluentBitConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterFluentBitConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFluentBitConfigSpec) DeepCopyInto(out *ClusterFluentBitConfigSpec) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		(*in).DeepCopyInto(*out)
	}
	in.ClusterInputSelector.DeepCopyInto(&out.ClusterInputSelector)
	in.ClusterFilterSelector.DeepCopyInto(&out.ClusterFilterSelector)
	in.ClusterOutputSelector.DeepCopyInto(&out.ClusterOutputSelector)
	in.ClusterParserSelector.DeepCopyInto(&out.ClusterParserSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFluentBitConfigSpec.
func (in *ClusterFluentBitConfigSpec) DeepCopy() *ClusterFluentBitConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterFluentBitConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFluentBitConfigStatus) DeepCopyInto(out *ClusterFluentBitConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFluentBitConfigStatus.
func (in *ClusterFluentBitConfigStatus) DeepCopy() *ClusterFluentBitConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterFluentBitConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInput) DeepCopyInto(out *ClusterInput) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInput.
func (in *ClusterInput) DeepCopy() *ClusterInput {
	if in == nil {
		return nil
	}
	out := new(ClusterInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterInput) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInputList) DeepCopyInto(out *ClusterInputList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInputList.
func (in *ClusterInputList) DeepCopy() *ClusterInputList {
	if in == nil {
		return nil
	}
	out := new(ClusterInputList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterInputList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInputSpec) DeepCopyInto(out *ClusterInputSpec) {
	*out = *in
	if in.Dummy != nil {
		in, out := &in.Dummy, &out.Dummy
		*out = new(input.Dummy)
		(*in).DeepCopyInto(*out)
	}
	if in.Tail != nil {
		in, out := &in.Tail, &out.Tail
		*out = new(input.Tail)
		(*in).DeepCopyInto(*out)
	}
	if in.Systemd != nil {
		in, out := &in.Systemd, &out.Systemd
		*out = new(input.Systemd)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInputSpec.
func (in *ClusterInputSpec) DeepCopy() *ClusterInputSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInputStatus) DeepCopyInto(out *ClusterInputStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInputStatus.
func (in *ClusterInputStatus) DeepCopy() *ClusterInputStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterInputStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOutput) DeepCopyInto(out *ClusterOutput) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOutput.
func (in *ClusterOutput) DeepCopy() *ClusterOutput {
	if in == nil {
		return nil
	}
	out := new(ClusterOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterOutput) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOutputList) DeepCopyInto(out *ClusterOutputList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterOutput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOutputList.
func (in *ClusterOutputList) DeepCopy() *ClusterOutputList {
	if in == nil {
		return nil
	}
	out := new(ClusterOutputList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterOutputList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOutputSpec) DeepCopyInto(out *ClusterOutputSpec) {
	*out = *in
	if in.Elasticsearch != nil {
		in, out := &in.Elasticsearch, &out.Elasticsearch
		*out = new(output.Elasticsearch)
		(*in).DeepCopyInto(*out)
	}
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(output.File)
		**out = **in
	}
	if in.Forward != nil {
		in, out := &in.Forward, &out.Forward
		*out = new(output.Forward)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(output.HTTP)
		(*in).DeepCopyInto(*out)
	}
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(output.Kafka)
		(*in).DeepCopyInto(*out)
	}
	if in.Null != nil {
		in, out := &in.Null, &out.Null
		*out = new(output.Null)
		**out = **in
	}
	if in.Stdout != nil {
		in, out := &in.Stdout, &out.Stdout
		*out = new(output.Stdout)
		**out = **in
	}
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(output.TCP)
		(*in).DeepCopyInto(*out)
	}
	if in.Loki != nil {
		in, out := &in.Loki, &out.Loki
		*out = new(output.Loki)
		(*in).DeepCopyInto(*out)
	}
	if in.Syslog != nil {
		in, out := &in.Syslog, &out.Syslog
		*out = new(output.Syslog)
		(*in).DeepCopyInto(*out)
	}
	if in.DataDog != nil {
		in, out := &in.DataDog, &out.DataDog
		*out = new(output.DataDog)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOutputSpec.
func (in *ClusterOutputSpec) DeepCopy() *ClusterOutputSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterOutputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOutputStatus) DeepCopyInto(out *ClusterOutputStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOutputStatus.
func (in *ClusterOutputStatus) DeepCopy() *ClusterOutputStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterOutputStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterParser) DeepCopyInto(out *ClusterParser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterParser.
func (in *ClusterParser) DeepCopy() *ClusterParser {
	if in == nil {
		return nil
	}
	out := new(ClusterParser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterParser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterParserList) DeepCopyInto(out *ClusterParserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterParser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterParserList.
func (in *ClusterParserList) DeepCopy() *ClusterParserList {
	if in == nil {
		return nil
	}
	out := new(ClusterParserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterParserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterParserSpec) DeepCopyInto(out *ClusterParserSpec) {
	*out = *in
	if in.JSON != nil {
		in, out := &in.JSON, &out.JSON
		*out = new(parser.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(parser.Regex)
		(*in).DeepCopyInto(*out)
	}
	if in.LTSV != nil {
		in, out := &in.LTSV, &out.LTSV
		*out = new(parser.LSTV)
		(*in).DeepCopyInto(*out)
	}
	if in.Logfmt != nil {
		in, out := &in.Logfmt, &out.Logfmt
		*out = new(parser.Logfmt)
		**out = **in
	}
	if in.Decoders != nil {
		in, out := &in.Decoders, &out.Decoders
		*out = make([]Decorder, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterParserSpec.
func (in *ClusterParserSpec) DeepCopy() *ClusterParserSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterParserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterParserStatus) DeepCopyInto(out *ClusterParserStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterParserStatus.
func (in *ClusterParserStatus) DeepCopy() *ClusterParserStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterParserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decorder) DeepCopyInto(out *Decorder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decorder.
func (in *Decorder) DeepCopy() *Decorder {
	if in == nil {
		return nil
	}
	out := new(Decorder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterItem) DeepCopyInto(out *FilterItem) {
	*out = *in
	if in.Grep != nil {
		in, out := &in.Grep, &out.Grep
		*out = new(filter.Grep)
		**out = **in
	}
	if in.RecordModifier != nil {
		in, out := &in.RecordModifier, &out.RecordModifier
		*out = new(filter.RecordModifier)
		(*in).DeepCopyInto(*out)
	}
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(filter.Kubernetes)
		(*in).DeepCopyInto(*out)
	}
	if in.Modify != nil {
		in, out := &in.Modify, &out.Modify
		*out = new(filter.Modify)
		(*in).DeepCopyInto(*out)
	}
	if in.Nest != nil {
		in, out := &in.Nest, &out.Nest
		*out = new(filter.Nest)
		(*in).DeepCopyInto(*out)
	}
	if in.Parser != nil {
		in, out := &in.Parser, &out.Parser
		*out = new(filter.Parser)
		(*in).DeepCopyInto(*out)
	}
	if in.Lua != nil {
		in, out := &in.Lua, &out.Lua
		*out = new(filter.Lua)
		(*in).DeepCopyInto(*out)
	}
	if in.Throttle != nil {
		in, out := &in.Throttle, &out.Throttle
		*out = new(filter.Throttle)
		(*in).DeepCopyInto(*out)
	}
	if in.RewriteTag != nil {
		in, out := &in.RewriteTag, &out.RewriteTag
		*out = new(filter.RewriteTag)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterItem.
func (in *FilterItem) DeepCopy() *FilterItem {
	if in == nil {
		return nil
	}
	out := new(FilterItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	if in.Daemon != nil {
		in, out := &in.Daemon, &out.Daemon
		*out = new(bool)
		**out = **in
	}
	if in.FlushSeconds != nil {
		in, out := &in.FlushSeconds, &out.FlushSeconds
		*out = new(int64)
		**out = **in
	}
	if in.GraceSeconds != nil {
		in, out := &in.GraceSeconds, &out.GraceSeconds
		*out = new(int64)
		**out = **in
	}
	if in.HttpPort != nil {
		in, out := &in.HttpPort, &out.HttpPort
		*out = new(int32)
		**out = **in
	}
	if in.HttpServer != nil {
		in, out := &in.HttpServer, &out.HttpServer
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}
