# .github/ct.yaml

remote: origin
target-branch: master   # change to main if your default branch is main

chart-dirs:
  - charts/fluent-operator

# Disabled to allow PRs from forks where master may be behind upstream
# Chart versioning is still enforced through maintainer review process
check-version-increment: false
validate-maintainers: true
