# charts/ct.yaml
remote: origin
target-branch: master

# Directories containing Helm charts (relative to repo root)
chart-dirs:
  - charts

# Optional: you can list charts to exclude if needed
excluded-charts: []

# Lint settings
check-version-increment: true
validate-maintainers: false
