version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: ci
      include: scope

  - package-ecosystem: "docker"
    directories:
      - "/cmd/fluent-manager"
      - "/cmd/fluent-watcher/fluentbit"
      - "/cmd/fluent-watcher/fluentd"
    schedule:
      interval: "daily"
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: "docker"
    directory: "/docs/best-practice/forwarding-logs-via-http"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod"
    directories:
      - "/"
    commit-message:
      prefix: build
      include: scope
    groups:
      k8s.io/*:
        patterns:
          - k8s.io/api
          - k8s.io/apimachinery
          - k8s.io/client-go
    schedule:
      interval: "weekly"
