version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/cmd/fluent-manager"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/cmd/fluent-watcher/fluentbit"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/cmd/fluent-watcher/fluentd"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/docs/best-practice/forwarding-logs-via-http"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod"
    directories:
      - "/"
    groups:
      k8s.io/*:
        patterns:
          - k8s.io/api
          - k8s.io/apimachinery
          - k8s.io/client-go
    schedule:
      interval: "weekly"
