# permissions for end users to edit clusteroutputs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusteroutput-editor-role
rules:
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusteroutputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusteroutputs/status
  verbs:
  - get
