# permissions for end users to view clusterfluentbitconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterfluentbitconfig-viewer-role
rules:
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterfluentbitconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterfluentbitconfigs/status
  verbs:
  - get
