# permissions for end users to edit clusterparsers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterparser-editor-role
rules:
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterparsers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterparsers/status
  verbs:
  - get
