# permissions for end users to edit clusterinputs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterinput-editor-role
rules:
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterinputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterinputs/status
  verbs:
  - get
