# permissions for end users to view clusterfilters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterfilter-viewer-role
rules:
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterfilters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterfilters/status
  verbs:
  - get
