apiVersion: v2
name: fluent-operator
description: Kubernetes operator for Fluent Bit and Fluentd—define collectors, pipelines, and outputs as custom resources.
keywords:
  - logging
  - fluent-bit
  - fluentd
  - operator
version: 0.0.0-dev.0  # This is a development chart which gets released and versioned in the fluent/helm-charts repo
# renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluent-operator
appVersion: 3.10.0  # x-release-please-version
icon: https://raw.githubusercontent.com/fluent/fluent-operator/master/docs/images/fluent-operator-icon.svg
home: https://github.com/fluent/fluent-operator
sources:
  - https://github.com/fluent/fluent-operator
maintainers:
  - name: wenchajun
    email: dehaocheng@kubesphere.io
  - name: marcofranssen
    email: marco.franssen@gmail.com
    url: https://marcofranssen.nl
  - name: joshuabaird
    email: joshbaird@gmail.com
