# Patch the ServiceMonitor to use HTTPS and certificates managed by cert-manager.
- op: replace
  path: /spec/endpoints/0/scheme
  value: https
- op: add
  path: /spec/endpoints/0/bearerTokenFile
  value: /var/run/secrets/kubernetes.io/serviceaccount/token
- op: add
  path: /spec/endpoints/0/tlsConfig
  value:
    # SERVICE_NAME and SERVICE_NAMESPACE will be substituted by kustomize
    serverName: SERVICE_NAME.SERVICE_NAMESPACE.svc
    insecureSkipVerify: false
    ca:
      secret:
        name: metrics-server-cert
        key: ca.crt
    cert:
      secret:
        name: metrics-server-cert
        key: tls.crt
    keySecret:
      name: metrics-server-cert
      key: tls.key
