# permissions for end users to edit clusterfilters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterfilter-editor-role
rules:
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterfilters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterfilters/status
  verbs:
  - get
