---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - clusterfilters
  - clusterfluentbitconfigs
  - clusterinputs
  - clustermultilineparsers
  - clusteroutputs
  - clusterparsers
  - filters
  - fluentbitconfigs
  - multilineparsers
  - outputs
  - parsers
  verbs:
  - list
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - collectors
  - fluentbits
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - collectors/finalizers
  - fluentbits/finalizers
  verbs:
  - update
- apiGroups:
  - fluentd.fluent.io
  resources:
  - clusterfilters
  - clusterfluentdconfigs
  - clusterinputs
  - clusteroutputs
  - filters
  - fluentdconfigs
  - inputs
  - outputs
  verbs:
  - list
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - clusterfluentdconfigs/status
  - fluentdconfigs/status
  - fluentds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentds
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentds/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
