
---
metadata:
  creationTimestamp: null
spec:
  group: ""
  names:
    kind: ""
    plural: ""
  scope: ""
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
