{{- if .Values.fluentbit.enable }}
{{- with .Values.fluentbit.output.prometheusMetricsExporter }}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: prometheus-exporter
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  match: {{ .match }}
  prometheusExporter:
    {{- toYaml .metricsExporter | nindent 4 }}
{{- end }}
{{- end }}
