{{- if .Values.Kubernetes }}
{{- if .Values.fluentbit.enable }}
{{- if .Values.fluentbit.output.kafka.enable }}
{{- with .Values.fluentbit.output.kafka }}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: kafka
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  kafka:
    brokers: {{ .brokers | quote }}
    topics: {{ .topics | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
