{{- if .Values.Kubernetes }}
{{- if .Values.fluentbit.enable }}
{{- with .Values.fluentbit.output.stackdriver }}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: stackdriver
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  stackdriver:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}

