{{- if .Values.Kubernetes -}}
{{- if .Values.fluentbit.input.nodeExporterMetrics.enabled -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: node-exporter-metrics
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  nodeExporterMetrics:
    tag: {{ .Values.fluentbit.input.nodeExporterMetrics.tag | default "node_metrics" }}
    scrapeInterval: {{ .Values.fluentbit.input.nodeExporterMetrics.scrapeInterval | default "15s" }}
    path:
      procfs: {{ .Values.fluentbit.input.nodeExporterMetrics.path.procfs | default "/host/proc" }}
      sysfs: {{ .Values.fluentbit.input.nodeExporterMetrics.path.sysfs | default "/host/sys" }}
{{- if .Values.fluentbit.input.nodeExporterMetrics.additionalConfig }}
{{ toYaml .Values.fluentbit.input.nodeExporterMetrics.additionalConfig | indent 4}}
{{- end }}

{{- end }}
{{- end }}
