{{- if .Values.Kubernetes -}}
{{- if .Values.fluentd.enable -}}
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: fluentd-output-buffer
  labels:
    output.fluentd.fluent.io/enabled: "true"
spec:
  outputs:
    - stdout: {}
      buffer:
        type: file
        path: /buffers/stdout.log
{{- end }}
{{- end }}