{{- if .Values.Kubernetes }}
{{- if .Values.fluentbit.enable }}
{{- with .Values.fluentbit.input.nodeExporterMetrics }}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: node-exporter-metrics
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  nodeExporterMetrics:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
