{{- if or .Values.fluentbit.enabled .Values.Kubernetes -}}
{{- if .Values.fluentbit.output.opentelemetry.enabled -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: fluentd-output-opentelemetry
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  opentelemetry:
{{ toYaml .Values.fluentbit.output.opentelemetry.config | indent 4}}
{{- end }}
{{- end }}
