{{- if .Values.Kubernetes -}}
{{- if .Values.fluentbit.enable -}}
{{- if .Values.fluentbit.input.nodeExporterMetrics -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: node-exporter-metrics
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  nodeExporterMetrics:
{{ toYaml .Values.fluentbit.input.nodeExporterMetrics | indent 4}}
{{- end }}
{{- end }}
{{- end }}
