{{- if .Values.operator.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-operator
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: fluent-operator
{{- end }}
