apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: erro-tail
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.2.0
spec:
  tail:
    tag: kube_erro
    path: /var/log/containers/*.log
    # Exclude logs from system components
    excludePath: /var/log/containers/*_kube*-system_*.log
    parser: docker
    refreshIntervalSeconds: 10
    memBufLimit: 5MB
    skipLongLines: true
    db: /fluent-bit/tail/pos-erro.db
    dbSync: Normal
