{{- if .Values.output.es.enabled -}}
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: es
  labels:
    logging.kubesphere.io/enabled: "true"
    logging.kubesphere.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  es:
    host: {{  .Values.output.es.host  }}
    port: {{  .Values.output.es.port  }}
    logstashPrefix: ks-logstash-log
    logstashFormat: true
    timeKey: "@timestamp"
  {{- end }}