{{- if .Values.Kubernetes -}}
apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: {{ .Values.containerRuntime }}
  labels:
    logging.kubesphere.io/enabled: "true"
    logging.kubesphere.io/component: logging
spec:
  systemd:
    tag: service.{{ .Values.containerRuntime }}
    path: /var/log/journal
    db: /fluent-bit/tail/docker.db
    dbSync: Normal
    systemdFilter:
      - _SYSTEMD_UNIT={{ .Values.containerRuntime }}.service
  {{- end }}