apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit-operator
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: fluentbit-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/name: fluentbit-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/name: fluentbit-operator
    spec:
      volumes:
      - name: env
        emptyDir: {}
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      initContainers:
      - name: setenv
        image: {{  .Values.deployment.volunmes.image.repository }}:{{  .Values.deployment.volunmes.image.tag }}
        command:
        - /bin/sh
        - '-c'
        - set -ex;
          echo DOCKER_ROOT_DIR=$(docker info -f '{{`{{ .DockerRootDir }}`}}') > /fluentbit-operator/fluent-bit.env
        volumeMounts:
        - name: env
          mountPath: /fluentbit-operator
        - name: dockersock
          readOnly: true
          mountPath: /var/run/docker.sock
      containers:
      - name: fluentbit-operator
        image: {{  .Values.fluentbitOperatorImage.repository   }}:{{  .Values.fluentbitOperatorImage.tag }}
        resources:
          {{ toYaml .Values.resources.operator.resources | nindent 10 }}
        volumeMounts:
        - name: env
          mountPath: /fluentbit-operator
      serviceAccountName: fluentbit-operator
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
