apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  image: {{  .Values.fluentbit.image  }}:{{  .Values.fluentbit.tag  }}
  {{- if .Values.imagePullSecrets }}
  imagePullSecrets:
  {{ toYaml .Values.imagePullSecrets | indent 4 }}
  {{- end }}
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  resources:
    {{- toYaml .Values.resources.fluentbit.resources | nindent 4  }}
  fluentBitConfigName: fluent-bit-config
  tolerations:
    - operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
