# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/fluentbit.fluent.io_clusterfluentbitconfigs.yaml
- bases/fluentbit.fluent.io_fluentbits.yaml
- bases/fluentbit.fluent.io_clusterinputs.yaml
- bases/fluentbit.fluent.io_clusterfilters.yaml
- bases/fluentbit.fluent.io_clustermultilineparsers.yaml
- bases/fluentbit.fluent.io_clusteroutputs.yaml
- bases/fluentbit.fluent.io_clusterparsers.yaml
- bases/fluentbit.fluent.io_collectors.yaml
- bases/fluentbit.fluent.io_fluentbitconfigs.yaml
- bases/fluentbit.fluent.io_filters.yaml
- bases/fluentbit.fluent.io_multilineparsers.yaml
- bases/fluentbit.fluent.io_outputs.yaml
- bases/fluentbit.fluent.io_parsers.yaml
- bases/fluentd.fluent.io_fluentds.yaml
- bases/fluentd.fluent.io_clusterfluentdconfigs.yaml
- bases/fluentd.fluent.io_fluentdconfigs.yaml
- bases/fluentd.fluent.io_filters.yaml
- bases/fluentd.fluent.io_clusterinputs.yaml
- bases/fluentd.fluent.io_inputs.yaml
- bases/fluentd.fluent.io_clusterfilters.yaml
- bases/fluentd.fluent.io_outputs.yaml
- bases/fluentd.fluent.io_clusteroutputs.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
