# permissions for end users to edit filters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filter-editor-role
rules:
- apiGroups:
  - logging.kubesphere.io
  resources:
  - filters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.kubesphere.io
  resources:
  - filters/status
  verbs:
  - get
