# permissions for end users to view inputs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: input-viewer-role
rules:
- apiGroups:
  - logging.kubesphere.io
  resources:
  - inputs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.kubesphere.io
  resources:
  - inputs/status
  verbs:
  - get
