# permissions for end users to view parsers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parser-viewer-role
rules:
- apiGroups:
  - logging.kubesphere.io
  resources:
  - parsers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.kubesphere.io
  resources:
  - parsers/status
  verbs:
  - get
