# permissions for end users to edit parsers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parser-editor-role
rules:
- apiGroups:
  - logging.kubesphere.io
  resources:
  - parsers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.kubesphere.io
  resources:
  - parsers/status
  verbs:
  - get
