name: WorkFlow for Building image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
      - '.github/workflows/**'
      - 'apis/**'
      - 'charts/**'
      - 'cmd/**'
      - 'controllers/**'
      - 'pkg/**'
      - 'hack/**'
      - 'manifests/setup/setup.yaml'
      - 'Makefile'

env:
  REGISTRY_REPO: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  operator-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for fluent-operator 
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image for fluent-operator 
        run: |
          tag=$(cat VERSION)
          make build-op -e FO_IMG=${{ secrets.DOCKERHUB_USERNAME }}/fluent-operator:$tag

  fluentbit-watcher-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for fluent-operator 
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.REGISTRY_REPO }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Image for fluentbit-watcher 
        run: |
          tag=$(cat VERSION)
          make build-fb-amd64 -e FB_IMG=${{ env.REGISTRY_REPO }}/fluentbit:$tag

  fluentd-watcher-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for fluent-operator 
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.REGISTRY_REPO }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Image for fluentbit-watcher 
        run: |
          tag=$(cat VERSION)
          make build-fd-amd64 -e FD_IMG=${{ env.REGISTRY_REPO }}/fluentd:$tag