name: WorkFlow for Building image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
      - ".github/workflows/**"
      - "apis/**"
      - "charts/**"
      - "cmd/**"
      - "controllers/**"
      - "hack/**"
      - "manifests/setup/setup.yaml"
      - "pkg/**"
      - "Makefile"

env:
  REGISTRY_REPO: 'kubesphere'

jobs:
  operator-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for Fluent Operator
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image for Fluent Operator
        run: |
          tag=$(cat VERSION | tr -d " \t\n\r")
          make build-op -e FO_IMG=${{ env.REGISTRY_REPO }}/fluent-operator:$tag

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for Fluent Bit and Fluentd
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Setting Environment Variables
        run: |
          echo "tag=$(cat VERSION | tr -d " \t\n\r")" >> $GITHUB_ENV 

      - name: Build and Push Image for Fluent Bit
        run: |
          FB_IMG=${{ env.REGISTRY_REPO }}/fluent-bit:$tag
          make build-fb-amd64 -e FB_IMG=$FB_IMG
          docker push $FB_IMG

      - name: Build and Push Image for Fluentd
        run: |
          FD_IMG=${{ env.REGISTRY_REPO }}/fluentd:$tag
          make build-fd-amd64 -e FD_IMG=$FD_IMG
          docker push $FD_IMG