name: Build-Custom-PullRequest

on:
  issue_comment:
    types: [created]
env:
  FB_IMAGE: fluent-bit:actions-pr-${{ github.event.issue.number }}
  OP_IMAGE: fluentbit-operator:actions-pr-${{ github.event.issue.number }}

jobs:
  push-check:
    runs-on: ubuntu-latest
    steps:
      - name: acknowledge deployment request to commenter
        id: check
        uses: khan/pull-request-comment-trigger@master
        with:
          trigger: "/push-custom"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}

  build-and-push:
    if: needs.push-check.outputs.triggered == 'true'
    runs-on: ubuntu-latest
    needs: push-check
    steps:
    - name: get pull request ref
      id: get_pull_request_ref
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/:repository/pulls/:issue_id
        repository: ${{ github.repository }}
        issue_id: ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/checkout@v2
      with:
        repository: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.repo.full_name }}
        ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Custom build and push
      if: needs.push-check.outputs.triggered == 'true'
      run: |
        echo "use buildx to build"
        make build-fb -e FB_IMG=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FB_IMAGE }}
        make build-op -e OP_IMG=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.OP_IMAGE }}
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Congratulations! The image of this pr is pushed.
          See ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FB_IMAGE }} and ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.OP_IMAGE }}